name: laynes_recetas
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.11.0+2
  firebase_storage: ^3.0.0
  image_picker: ^0.6.0+8
  date_format: ^1.0.6
  intl: ^0.15.8
  flutter_launcher_icons: ^0.7.2
  firebase_auth:
  google_sign_in:
  http: ^0.12.0+2
  firebase_core: ^0.4.0+3
  flutter_auth_buttons: ^0.5.0
  geoflutterfire: ^2.0.3+4
  location: ^2.3.5
  google_maps_flutter: ^0.5.15+1
  font_awesome_flutter: ^8.4.0
  rxdart: ^0.22.0
  geocoder: ^0.1.2
  cached_network_image:
  circle_wheel_scroll: ^0.0.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter


  #meta: ^1.1.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/comi.png"

flutter:
  assets:
  - assets/images/firebase-logo.png
  - assets/images/flutter-logo.png
  - assets/images/pluse-icon.png


  uses-material-design: true

